### ISSUE TITLE
I commented on your DMCA takedown

### ISSUE THREAD

**Issue by flarn2006** [Kloct/tera-auth-ticket#4]
https://github.com/github/dmca/commit/6363e67869e11be0e8e7b96ae60b59f7fd93edfe

Just wanted to bring your attention to my comment linked above. This has nothing to do with this repository specifically, but I don't know of any better way to send you a message via Github.

Also, again, I'm not a lawyer, and this shouldn't be taken as legal advice. So if you do decide to file a counter-notice based on my claim, I'm not responsible if it ends up backfiring.

**Comment by Kloct** [comment]
Hey thanks for reaching out.
I responded to your post in the commit comments.
